language: ruby
before_install:
  - travis_retry gem install bundler
rvm:
  - "2.0.0"
gemfile: Gemfile
services: rabbitmq 
script: 
  - bundle
  - bundle install
  - cd test; 
  - ruby test_estorm.rb
  - ruby test_consumer.rb
  - ruby test_single.rb
notifications:
  recipients:
    - scott.sproule@estormtech.com
  email:
    on_success: change
    on_failure: always
addons:
  code_climate:
    repo_token: 5370a46bd88553652cb01e8297177d1ec5f28714ba9fdc0c473dfbdb7000cc76
